### ISSUE TITLE
Question about the two generation methods.

### ISSUE THREAD

**Issue by zlwang-cs** [shangdatalab/OpenAITool#1]
A quick question, what is the difference between the `generate_consecutive` and `generate`? Are they designed for difference cases or doing the same thing but with different strategies?

Also in this line: https://github.com/shangdatalab/OpenAITool/blob/b47257e195e8adb7815025e74283cc8bc9fb55ae/openai_tools.py#L245C24-L245C24

Is this behavior intended? I mean the `messages` will be so long after a few iterature.

**Comment by zhang-yu-wei** [comment]
`generate_consecutive` is intended to take in a list of prompts (like step1 and then step2) while `generate` takes only one prompt. Although I am not sure whether there is a easier way.

And I think `messages` will be reset after this line: https://github.com/shangdatalab/OpenAITool/blob/b47257e195e8adb7815025e74283cc8bc9fb55ae/openai_tools.py#L239

**Comment by zlwang-cs** [comment]
I see. I find out that this is to support an iterative dialogue. Thanks!
